function csvImportValues = importCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  csvImportValues =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  csvImportValues = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  csvImportValues = importfile("/Users/ioannis/Documents/git/codec-comparison/csv/h264/S11AirAcrobatic_1920x1080_60fps_10bit_420_decoded_crf_15_1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Jan-2021 12:43:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SystemTime", "RDTSC", "ElapsedTimesec", "CPUUtilization", "CPUFrequency_0MHz", "CPUMinFrequency_0MHz", "CPUMaxFrequency_0MHz", "CPURequstedFrequency_0MHz", "ProcessorPower_0Watt", "CumulativeProcessorEnergy_0Joules", "CumulativeProcessorEnergy_0mWh", "IAPower_0Watt", "CumulativeIAEnergy_0Joules", "CumulativeIAEnergy_0mWh", "PackageTemperature_0C", "PackageHot_0", "CPUMinTemperature_0C", "CPUMaxTemperature_0C", "DRAMPower_0Watt", "CumulativeDRAMEnergy_0Joules", "CumulativeDRAMEnergy_0mWh", "PackagePowerLimit_0Watt", "GTFrequencyMHz", "GTRequstedFrequencyMHz"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "SystemTime", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "SystemTime", "EmptyFieldRule", "auto");

% Import the data
csvImportValues = readtable(filename, opts);

csvImportValues( any(ismissing(csvImportValues),2), :) = [];

end