function cpuUtilisation = importCPUUtilisation(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VARNAME1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as column vectors.
%
%  VARNAME1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  VarName1 = importfile("/Users/ioannis/Documents/git/codec-comparison/samplecpu/h264/S11AirAcrobatic_1920x1080_60fps_10bit_420_decoded_crf_15_1.log", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Jan-2021 20:38:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
cpuUtilisation = tbl.VarName1;
end